import React, { useEffect } from 'react';

export default function AIEngineSchema() {
  useEffect(() => {
    // Prevent duplicate injections on fast hot-reloads
    const existingScript = document.getElementById('rankai-geo-schema');
    if (existingScript) return;

    const script = document.createElement('script');
    script.id = 'rankai-geo-schema';
    script.type = 'application/ld+json';
    
    // The structured schema map generated by RankAI GEO
    const schemaData = [
      {
        "@context": "https://schema.org",
        "@type": "Organization",
        "@id": "https://www.gridpulse.co.in/#organization",
        "name": "Grid Pulse AI",
        "url": "https://www.gridpulse.co.in/"
      },
      {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "@id": "https://www.gridpulse.co.in/#website",
        "url": "https://www.gridpulse.co.in/",
        "name": "Grid Pulse AI",
        "publisher": {
          "@id": "https://www.gridpulse.co.in/#organization"
        }
      },
      {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "@id": "https://www.gridpulse.co.in/#app",
        "name": "Solar Panel & Savings Calculator by Grid Pulse AI",
        "url": "https://www.gridpulse.co.in/",
        "operatingSystem": "Web",
        "isAccessibleForFree": true,
        "publisher": {
          "@id": "https://www.gridpulse.co.in/#organization"
        }
      },
      {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "@id": "https://www.gridpulse.co.in/#webpage",
        "url": "https://www.gridpulse.co.in/",
        "name": "Grid Pulse AI | Free DIY Solar Panel & Savings Calculator",
        "isPartOf": {
          "@id": "https://www.gridpulse.co.in/#website"
        },
        "about": {
          "@id": "https://www.gridpulse.co.in/#app"
        },
        "mainEntity": {
          "@id": "https://www.gridpulse.co.in/#app"
        }
      }
    ];

    script.text = JSON.stringify(schemaData);
    document.head.appendChild(script);

    return () => {
      // Clean up when the component unmounts
      const scriptToRemove = document.getElementById('rankai-geo-schema');
      if (scriptToRemove) {
        document.head.removeChild(scriptToRemove);
      }
    };
  }, []);

  return null; // Side-effect operation only; renders no visible HTML structures
}
